export interface IAvailablePlace {
  id: string;
  name: string;
  appointmentUrl: string;
  phone: string;
  address: string;
  updatedAt: Date;
}

export interface IAvailablePlaceResponse {
  available: boolean;
  phone: string;
  address: string;
}

// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface IShoppersDrugmartResponse {
  id: number;
  storeNumber: number;
  name: string;
  code: string;
  trackingPhone: string;
  license: string;
  associate: string;
  associate_gender1: string;
  associate2: string;
  associate_gender2: string;
  associate3: string;
  associate_gender3: string;
  storeType: string;
  distance: number;
  longitude: number;
  latitude: number;
  pharmasists: string;
  image: string;
  smallImage: string;
  address: string;
  address2: string;
  address3: string;
  city: string;
  postalCode: string;
  province: string;
  email: string;
  phone: string;
  fax: string;
  storeHours: string[];
  postalHours: any[];
  weekDays: null;
  todayHours: string;
  pinColor: string;
  beautyBoutique: boolean;
  fluShot: boolean;
  featuredServices: any[];
  schedulerLink: string;
  allDay: boolean;
  Inventory: number;
  holidayHours: any[];
  currentlyOpen: boolean;
  storeHoursTicks: StoreHoursTick[];
  noHoliday: string[];
  googleOpeningHours: { [key: string]: string };
  IsMurale: boolean;
  FlusShotAvailableNow: boolean;
}

export interface StoreHoursTick {
  ticksOpen: number;
  ticksClose: number;
}
